### ISSUE TITLE
No activation function in MLP?

### ISSUE THREAD

**Issue by Wenlin-Chen** [YujiaBao/ls#1]
Hi, thanks for making the code and data available for this interesting paper! 

I have one question about your implementation of MLP. It says in the paper that ReLU activation functions are applied to the hidden units of the MLP, but there seems to be no activation functions in your [implementation](https://github.com/YujiaBao/ls/blob/5ce440778532affee0b88dd9dd54d684f0163c38/ls/models/mlp.py#L40)?

**Comment by YujiaBao** [comment]
Yes, the ReLU activation was missing. Thank you for identifying this bug! It has been fixed now :)
